group: github.com/zhao-kun/mqtt-bench
version: v1.0.1
kind: publish
metaData:
  name: task-demo
spec:
  brokerAddr: 127.0.0.1:1883
  clientId: test
  connection: 100
  userName: admin
  password: admin
  payload: "hello world"
  tenantName: "zlg"
  infoModelId: "google"
  thinkTime: 5000
  duration: 60
