group: github.com/zhao-kun/mqtt-bench
version: v1.0.1
kind: publish
metaData:
  name: task-demo
spec:
  brokerAddr: ["127.0.0.1:1883"]
  clientId: client_id
  connection: 100
  userName: admin
  password: bbbb
  topicTemplate: /prefix/${tenantName}/${infoModelId}/${thirdThingsId}
  thinkTime: 5000
  duration: 60
  payload: "hello world"
  data:
    tenantName: "google"
    infoModelId: "demo_v1"
    thirdThingsId: thirdThingsID
