group: github.com/zhao-kun/mqtt-bench
version: v1.0.1
kind: publish
metaData:
  name: task-demo
spec:
  brokerAddr: ["127.0.0.1:1883"]
  clientId: client_id
  thirdThingsId: thirdThingsID
  connection: 100
  userName: admin
  password: bbbb
  payload: "hello world"
  tenantName: "google"
  infoModelId: "demo_v1"
  thinkTime: 5000
  duration: 60
