group: github.com/zhao-kun/mqtt-bench
version: v1.0.1
kind: publish
metaData:
  name: task-demo
spec:
  brokerAddr: ["127.0.0.1:1883"]
  clientId: client_id
  connectionPerConnection: 1
  dynamicToken: 
    url: http://localhost:8080/v1/
    payload: '{"username": "${tenantName}", "password": "${password}" }'
    tokenExtractor: ".data.token"
  userName: admin
  password: bbbb
  topicTemplate: /prefix/${tenantName}/${infoModelId}/${thirdThingsId}
  thinkTime: 5000
  duration: 60
  thingsPayloads:
   "google": "hello world"
  thingsInfo:
  - tenantName: "google"
    infoModelId: "demo_v1"
    thirdThingsId: thirdThingsID
    password: "things_password"
